version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8050:8050"
    networks:
      - llmnet
    extra_hosts:
      - "model-runner.docker.internal:host-gateway"

networks:
  llmnet:
    driver: bridge

