apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    io.kompose.service: db
spec:
  type: ClusterIP
  selector:
    io.kompose.service: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432